kind: Secret
apiVersion: v1
metadata:
  name: mysql
  namespace: itzhakkakon-dev
  uid: 20637b4d-d799-4d41-9b52-66ae90452c39
  resourceVersion: '3410825368'
  creationTimestamp: '2025-08-14T12:55:36Z'
  labels:
    app: mysql
    app.kubernetes.io/component: mysql
    app.kubernetes.io/instance: mysql
    app.openshift.io/runtime: mysql-database
    template: mysql-persistent-template
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  managedFields:
    - manager: oc.exe
      operation: Update
      apiVersion: v1
      time: '2025-08-14T12:55:36Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:database-name': {}
          'f:database-password': {}
          'f:database-root-password': {}
          'f:database-user': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/generated-by': {}
            'f:template.openshift.io/expose-database_name': {}
            'f:template.openshift.io/expose-password': {}
            'f:template.openshift.io/expose-root_password': {}
            'f:template.openshift.io/expose-username': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.openshift.io/runtime': {}
            'f:template': {}
        'f:type': {}
data:
  database-name: c2FtcGxlZGI=
  database-password: VGlSVkJ4TU1OZ1gyYWJibw==
  database-root-password: WTM3b2MxVVVTWHJia1FnTg==
  database-user: dXNlcjFZNw==
type: Opaque
